// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname);

// Ignore transient build folders generated by gradle/ndk to avoid watcher ENOENT issues
const androidBuildRegex = /.*[/\\]android[/\\]build[/\\].*/;
if (Array.isArray(config.resolver.blockList)) {
  config.resolver.blockList.push(androidBuildRegex);
} else if (config.resolver.blockList) {
  config.resolver.blockList = [config.resolver.blockList, androidBuildRegex];
} else {
  config.resolver.blockList = [androidBuildRegex];
}

module.exports = config;
